apiVersion: v1
kind: Service
metadata:
  name: citus-master-service
  labels:
    app: citus
    role: master
spec:
  selector:
    app: citus
    role: master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
