apiVersion: v1
kind: Service
metadata:
  name: citus-worker-service
  labels:
    app: citus
    role: worker
spec:
  selector:
    app: citus
    role: worker
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
